# Generated by Django 4.1.3 on 2023-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="categore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("link", models.URLField()),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "categore",
            },
        ),
        migrations.CreateModel(
            name="zeenews",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("link", models.URLField()),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "zeenews",
            },
        ),
    ]
